/**
 * Build script: Reads .env and generates js/firebase-config.js
 * Usage: node build-config.js
 */
const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
    console.error('❌ .env file not found! Create .env with Firebase config values.');
    console.error('   Copy .env.example to .env and fill in your values.');
    process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        env[key.trim()] = valueParts.join('=').trim();
    }
});

// Validate required keys
const required = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_DATABASE_URL',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID'
];

const missing = required.filter(k => !env[k]);
if (missing.length > 0) {
    console.error('❌ Missing environment variables:', missing.join(', '));
    process.exit(1);
}

// Generate firebase-config.js
const output = `// ⚠️ AUTO-GENERATED — Do not edit manually!
// Generated by: node build-config.js
// Source: .env (not committed to git)

const CONFIG = {
    apiKey: "${env.FIREBASE_API_KEY}",
    authDomain: "${env.FIREBASE_AUTH_DOMAIN}",
    databaseURL: "${env.FIREBASE_DATABASE_URL}",
    projectId: "${env.FIREBASE_PROJECT_ID}",
    storageBucket: "${env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${env.FIREBASE_APP_ID}"
};

export default CONFIG;
`;

const outPath = path.join(__dirname, 'js', 'firebase-config.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log('✅ js/firebase-config.js generated successfully');
